### PR TITLE
Update ANNOUNCE for 2.2.1

### PR DESCRIPTION
**Pull request by qmfrederik**
This updates ANNOUNCE for 2.2.1 and copies the current contents to ANNOUNCE.2.2.  I couldn't find anything 2.3-specific in ANNOUNCE (https://github.com/gnustep/libobjc2/issues/281#issuecomment-1967071728), sorry if I missed that.

I'm not too familiar with the release process in this repo, so all feedback is welcome.

Released to #281

### CODE REVIEW

**Comment by davidchisnall** [comment]
Sorry for the delay.  The target of this needs to be the 2.2 branch and we need to cherry pick all of the things that we want in 2.2.1 into the 2.2 branch.  We then do a release by creating a v2.2.1 tag from the head of the 2.2 branch.

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
Draft release here:

https://github.com/gnustep/libobjc2/releases/edit/untagged-debddff89ebe8e9e6160

Feel free to hit the publish button if you're happy with it!

**Comment by qmfrederik** [comment]
Thanks @davidchisnall !

**Comment by qmfrederik** [comment]
Here's the PR to get it included in MSYS2: https://github.com/msys2/MINGW-packages/pull/20406

**Pull request merged**
