### PR TITLE
Update blocks_runtime.h

### PR DESCRIPTION
**Pull request by zenny-chen**
Get Compatible with Apple LLVM.

### CODE REVIEW

**Comment by zenny-chen** [comment]
Let Blocks API compatible with Apple LLVM.

**Comment by davidchisnall** [comment]
The middle commit was passing CI tests, but this one doesn't seem to build.

**Comment by danilaml** [comment]
@davidchisnall can you also merge https://github.com/gnustep/libs-base/pull/13 ? Currently you'll get incompatible headers when building from latest source since they'll contain different type signatures.

**Comment by davidchisnall** [comment]
Merged, though -base shouldn't actually need that - a better fix would be to make the -base declarations conditional on `!__has_include(<objc/blocks_runtime.h>)`

**Pull request merged**
