### PR TITLE
Minimal reproducing test case

### PR DESCRIPTION
**Pull request by dlobron**
This creates a test number 47 in the unit test suite, which fails with an exception.  The exception reproduces the bug.

### CODE REVIEW

**Comment by davidchisnall** [comment]
This seems to refer to a `ModTest.{m,h}`, which are not part of the pull request.

**Comment by dlobron** [comment]
Ah, drat, I forgot to include them in the PR. I’m away from computer for this week, but I will add them as soon as I can. The files essentially duplicate the Test class from Test.{m|h}, but with interface and implementation separated to allow inclusion in multiple compilation units.

David

**Comment by davidchisnall** [comment]
Never mind.  I've managed to delete about 90% of the code and have a minimal test case.

**Comment by dlobron** [comment]
Thanks, David. Apologies for the extra code: it was left from earlier experiments. 

David

**Pull request merged**
